### PR TITLE
add docker-compose env + update readme

### PR DESCRIPTION
**Pull request by Sonlis**
# Add docker environment
To simplify the setup of local environment, uses docker-compose to setup the project and database. 

## Modification to source code
Even though I mostly added support for docker-compose, which is not involved in the source code, I had to modify 2 small things. Both modification add support for container while keeping support for local environment setup.

1. The sequelize function could not find the database if the host was set to localhost (obviously), so added a check of env variable in `server/models/index.js` to reach the correct endpoint.
2. Set the server_host variable in `config/config.project.js` to localhost if the env variable is set: if using ip.address, the container will serve files from its own ip address, which is not routable outside the container network and hence not reachable from localhost.

From my tests on MacOS, I could run the app with both `docker-compose` and `npm start`.

### CODE REVIEW

**Comment by jviitamo** [comment]
Some problems are occuring with windows. Running `docker-compose up` results in a following error:

image

Running `npm start` with mysql server started manually works just fine.

**Comment by Sonlis** [comment]
Seems like it's not picking up the env variables, I'm investigating that.

**Comment by Sonlis** [comment]
Ok, I am absolutely stupid and forgot to add the env variable in env.md that I added locally for it to work :D 

I fixed that, and added some volumes to be shared with the container so you don't need to re-build the container every time you wish to see your changes in the browser.

**Comment by jviitamo** [comment]
Nice job! Working great now. You made changes so that containers don't need to be re-built after every change, so should that be updated to the `README.md`?

**Comment by jviitamo** [comment]
Now looks excellent. Ready to be merged.

**Pull request merged**
